# -*- eval: (org-fragtog-mode 1); -*-
#+title: Mathematical definitions
#+options: tex:t

* Group

A *group* is a set G endowed with a binary operation $(\cdot)$ such that the following properties hold:
- *Closure:* $\forall a,b \in G, \; a \cdot b \in G$ .
- *Associativity:* $\forall a,b,c \in G, \; a \cdot (b \cdot c) = (a \cdot b)\cdot c$ .
- *Existence of identity element:* $\exists e \in G \; ; \; \forall a \in G, \; a \cdot e = e \cdot a = a$ .
- *Existence of inverse element:* $\forall a \in G, \; \exists b \in G \; ; \; a \cdot b = b \cdot a = e$ .

A *group* is said to be *commutative* or *abelian* if $\forall a,b \in G, \; a \cdot b = b \cdot a$ .

A subset $H$ of $G$ is a *subgroup* of $\langle G, \cdot \rangle$ , if it is closed under $(\cdot)$ induced. The *trivial subgroup* of any group is the set consisting of just the identity element.

The *order* of a group $\langle G, \cdot \rangle$ is the cardinality of the set $G$ .

A subgroup $H$ of $G$ can be used to decompose $G$ in uniformly sized and disjoints subsets called *cosets*. Given an element $g \in G$ :
- A *left coset* is defined by $gH := \{g \cdot h \; ; \; h \in H\}$ .
- A *right coset* is defined by $Hg := \{ h \cdot g \; ; \; h \in H\}$ .

* Rings and Fields
A *ring* is a set, together with two binary operations that we denote $+$ and $\ast$ , such that:
- $\langle R, + \rangle$ is an abelian group.
- $\ast$ is associative.
- $\ast$ is distributive over $+$ .

A ring is denoted by $\langle R, +, \ast \rangle$ or, simply, $R$ if the operations are clear from the context.

A ring is said to be *commutative* if its $\ast$ operation is commutative.

A ring is said to be *with unity* if $\ast$ has an identity element. We shall denote it by $1$ and call it *unity*.

A *division ring* is a ring with unity $R$ , where, $\forall r \in R, \; \exists s \in R \; ; \; r\ast s=1$ .

A *field* is a commutative division ring.

* Number fields
For $K,L$ two fields, we denote by $L/K$ a *field extension* if $K \subseteq L$. Then $L$ is said to be an *extension field* over $K$, or just and *extension* over $K$.

Note that a field extension $L/K$, $L$ has a structure of a vector space over $K$, where vector addition is in $L$ and scalar multiplication is defined as: for $a \in K, \; v \in L$ we have $av \in L$. The dimension of $L$ as a vector space is called *degree* and is denoted by $[L:K]$.

We call a *simple extension* when the extension is generated by the adjunction of a single element. We denote it by $L = K(\theta)$, where $\theta \in L$ is the added element. The same idea is applied for rings and it is denoted by $L = K[\theta]$.

A field extension is called *number field* when it is over the rational field $\mathbb{Q}$.

Let $\alpha \in L$, where $L/K$ is a field extension. We say that $\alpha$ is *algebraic over* $K$ if $\exists p \in K[X] \; ; \; p(\alpha) = 0$. $p$ is said to be *the minimal polynomial of* $\alpha$ *over* $K$ denoted by $p_\alpha$. If $\alpha \in L=\mathbb{Q}(\theta)$, we simply call $\alpha$ an *algebraic number*.


*EXAMPLE:* It is known that $\mathbb{Q}$ is a field. If we add $\sqrt{2}$ to the set, we can build a new field adding also all the powers and multiples of $\mathbb{Q}$. This new field is denoted by $\mathbb{Q}(\sqrt{2})$, note that $\sqrt{2}$ is algebraic and its minimal polynomial $p_{\sqrt{2}} = x^2 - 2$. All elements of $\mathbb{Q}(\sqrt{2})$ are of the form $\{a+b\sqrt{2} \; | \; a,b \in \mathbb{Q}\}$ and one of its basis is ${1, \sqrt{2}}$, so it has degree $2$.


*EXAMPLE*: If we add $\sqrt[3]{2}$ to $\mathbb{Q}$ instead, its elements would have the form $\{a+b\sqrt[3]{2} + c \sqrt[3]{4} \; | \; a,b,c \in \mathbb{Q} \}$,so one of its basis is $\{1, \sqrt[3]{2}, \sqrt[3]{4} \}$, $p_\alpha = x^3 - 2$ and its degree is $3$.
