#+language: en
#+latex_class: ic-tese-v3
#+latex_class_options: [Ingles]
#+latex_compiler: latexmk
#+OPTIONS: tex:t author:nil date:nil toc:nil 
#+STARTUP: latexpreview fold
#+LATEX_HEADER: \input{./config/math-config}

\autora{Laura Viglioni}

\title{The Dissertation or Thesis Title in English}

\orientador{Prof. Dr. Ricardo Dahab}

\mestrado

\datadadefesa{22}{04}{1500}

\paginasiniciais



* Introduction

* Mathematical Background 
  
** Groups
  
   \begin{definition}
  A \textbf{group} is a set $G$ closed under a binary operation $\cdot$ defined on $G$ such
  that:
  \begin{itemize}
  \item \textbf{Associativity: } $\forall a,b,c \in G, \; a\cdot(b\cdot c) = (a\cdot b)\cdot c$
  \item \textbf{Identity element: } $\exists e \in G \; ; \; \forall a \in G, \; a\cdot e = e\cdot a = a$
  \item \textbf{Inverse element: } $\forall a \in G, \; \exists b \in G \; ; \; a\cdot b = b \cdot a = e$
  \end{itemize}
And it is denoted by $\langle G,\cdot\rangle$, or simply $G$ if the operation is implied.
\end{definition}

   \begin{definition}
     A group is said to be \textbf{commutative} or \textbf{abelian}
     if $\forall a, b \in G, \; a\cdot b = b\cdot a$
   \end{definition}

   \noindent
   A group is called *additive* or *multiplicative* if its
   operation is addition or multiplication, respectively.

   \begin{definition}
     A subset $H$ of $G$ is a \textbf{subgroup} of $\langle G,\cdot \rangle$ if it is
     closed under $\cdot$ induced by $\langle G,\cdot \rangle$.
   \end{definition}

   \begin{definition}
     The \textbf{order} of a group $\langle G,\cdot\rangle$ is the cardinality of the set $G$.
   \end{definition}

   \begin{definition}
     A subgroup $H$ of $G$ can be used to decompose $G$ in uniform sized and
     disjoints subsets called \textbf{cosets}. Given an element $g \in G$:
     \begin{itemize}
     \item A \textbf{left coset} is defined by $gH := \{g\cdot h \; ; \; h \in H\}$
     \item A \textbf{right coset} is defined by $Hg := \{h\cdot g \; ; \; h \in H\}$
     \end{itemize}
   \end{definition}

** Rings and Fields
   
   \begin{definition}
  A \textbf{ring} is a set together with two binary operations, we will note by
  $+$ and $*$ and call it addition and multiplication, respectively, such that:
  \begin{itemize}
  \item $\langle R,+\rangle$ is an abelian group.
  \item $*$ is associative
  \item $*$ is distributive over $+$
  \end{itemize}

  And it is denoted by $\langle R,+,*\rangle$, or simply $G$ if the operations are implied.
\end{definition}

   \begin{definition}
     A ring is said to be \textbf{commutative} if its $*$ operation is commutative.
   \end{definition}

   \begin{definition}
     A ring is said to be \textbf{with unity} if $*$ has a identity element. We
     shall note it by $1$ and it is called \textbf{unity}.

   \end{definition}

   \begin{definition}
     A \textbf{division ring} is a ring R where $\forall r \in R, \; \exists s \in R \; ; \; r*s = 1$.
   \end{definition}

   \begin{definition}
     A \textbf{field} is a commutative division ring.
   \end{definition}

** Lattices

   \begin{definition}
  A Lattice $\Lambda \subset \R^n$ is a subgroup of the additive group $\R^n$
\end{definition}

   In other words, given $m$ linear independent vectors in $\R^n$, the set
   $\{v_1, v_2, ..., v_m\}$ is called a \textbf{basis} for $\Lambda$ and the Lattice may defined
   by:

   \begin{definition}
     \begin{equation*}
       \Lambda := \left\{x = \sum_{i=1}^m{\lambda_iv_i} \in \R^n \; | \; \lambda_i \in \Z\right\}
     \end{equation*}

   \emph{I.e.}, any $\lambda \in \Lambda$ can be written as $\lambda = Mv$ where $M$ is the
   \textbf{generator matrix} of $\Lambda$ where each row is a vector from the basis and
   $v \in \Z^n$.
   \end{definition}

** Number Fields

   \begin{definition}
  Let $K$ and $L$ be two fields, $L$ is said to be a \textbf{field extension} of
  $K$ if $L \subseteq K$ and we denote it by $L/K$
\end{definition}

   Note that in a field extension $L/K$, $L$ has a structure of a vector space over
   $K$, where vector addition is in $L$ and scalar multiplication $a \in K, \; v \in L
   \; \implies av \in L$. The dimension of $L$ as a vector space is called
   \textbf{degree} and it is denoted by $[L:K]$.

   \begin{definition}
     A field extension is called \textbf{number field} when it is over $\Q$.
   \end{definition}

   \begin{definition}
     Let $\alpha \in L$ where $L/K$ is a field extension. We say that $\alpha$ is
     \textbf{algebraic over $K$} if $\exists p \in K[X] \;;\; p(\alpha) = 0$. $p$ is said to be
     \textbf{the minimal polynomial of $\alpha$ over $K$} denoted by $p_\alpha$. If $\alpha \in L =
     \Q[\theta]$, we simply call $\alpha$ an \textbf{algebraic number}.
   \end{definition}

   \begin{example}
     It is known that $\Q$ is a field. If we add $\sqrt{2}$ to the set, we
     can build a new field adding also all the powers and multiples of
     $\Q$. This new field is denoted by $\Q[\sqrt{2}]$, note that
     $\sqrt{2}$ is algebraic and its minimal polynomial $p_{\sqrt{2}} = x^2-2$. All
     elements of $\Q[\sqrt{2}]$ are in the form $\{a+b\sqrt{2} \;|\; a,b \in
     \Q\}$ and one of its basis is $\{1, \sqrt{2}\}$, so it has degree is
     $2$.
   \end{example}

   \begin{example}
     If we add $\sqrt[3]{2}$ to $\Q$ instead, its elements would have the
     form $\{a + b\sqrt[3]{2} + c\sqrt[3]{4} \;|\; a,b,c \in \Q\}$, so one of
     its basis is $\{1 ,\sqrt[3]{2} ,\sqrt[3]{4}\}$, $p_\alpha = x^3 - 2$ and its degree
     is $3$.
   \end{example}

   \begin{theorem}
     [add font 45 p.40] If $K$ is a number field, then $K = \Q[\theta]$ for some
     algebraic number $\theta \in K$, called primitive element.
   \end{theorem}

   Then we conclude that $\{1, \theta, \theta^2, ... , \theta^{n-1}\}$ is a basis for the vector
   space $K = \Q[\theta]$ over $\Q$. Note that we can represent an number $a \in K$ as a linear combination of $\theta$, /i.e/ $a = \sum^n_{i=0}{a_i\theta^i}$ or as a polynomial $a(x) = \sum^n_{i=0}{a_ix^i}$.

   \begin{definition}
   A number $\alpha$ is said to be an \textbf{algebraic integer} if $ p \in \Z[X] \;;\; p(\alpha) = 0$. The set of all algebraic integers of $K$ forms a ring called \textbf{ring of ingegers} of $K$ and is denoted by $\Ok$.
   \end{definition}
   
   \begin{definition}
   An \textbf{integral basis} is a basis for a ring of integers. 
   \end{definition}

** Twisted Embeddings
*** Embeddings
   
   \begin{definition}
   Let $K$ and $L$ be two field extensions and a homomorphism $\phi: K \rightarrow L$. $\phi$ is said to be a \textbf{$\Q$-homomorphism} if $\phi(a) = a, ; \forall a \in \Q$ 
   \end{definition}

   \begin{definition}
   A $\Q-homomorphism ; \phi: K \rightarrow \C$ is callend an \textbf{embedding}.
   \end{definition}

   \begin{theorem}
   [inserir fonte 45, p.41] If $K$ is a number field with degree $n$ then there are
   exactly $n$ embeddings $\sigma_i : K \rightarrow \C$ where by $\sigma_i(\theta) =
   \theta_i$ where $\theta_i \in \C$ is a distinct zero of the $K$'s
   mininum polynomial.
   \end{theorem}

   \begin{definition}
Let $\{\sigma_i\}_n$ the possible embeddings of a number field $K$. Let $r$ the number of embeddings with real images and $2s$ the complex ones, then
$r + 2s = n$. The pair $\left(r,s\right)$ is called \textbf{signature} of $K$.
\end{definition}

                     \begin{definition}\label{def:canonical-embedding}
                  The homomorphism $\sigma: K \rightarrow \R^r \times \C^s$, where $(r,s)$ is the signature of $K$, is
                  said to be the \textbf{canonical embedding} and is defined by:
                  $$
                  \sigma(x) = \left(\sigma_1(x), ... , \sigma_r(x), \sigma_{r+1}(x), ..., \sigma_{r+s}(x) \right)
                  $$

                  Note that we could rewrite the canonical embedding as $\sigma : K \rightarrow \R^n$
                  $$
                  \sigma(x) = \left( \sigma_1(x), ... , \sigma_r(x), \Re(\sigma_{r+1}(x)), \Im(\sigma_{r+1}(x)), ...,
                    \Re(\sigma_{r+s}(x)), \Im(\sigma_{r+s}(x)) \right)
                  $$

                  For now on we will denote it simply by:

                  $$
                  \sigma(x) = \left( \sigma_1(x), \dots , \sigma_r(x), \sigma_{r+1}(x), \dots, \sigma_{r+2s}(x) \right)
                  $$

                  \end{definition}
            
*** Algebraic Lattices
    
            \begin{theorem}[adicionar citaçao 45, p155]\label{theo:algebraic-lattice}
            Let $\{\omega_1,...,\omega_n\}$ be an integral basis of $K$, The $n$ vectors $v_i = \sigma(\omega_i)
            \in \R^n$ are linearly independent, so thety define a full rank algebraic lattice
            $\Lambda = \Lambda(\Ok) = \sigma(\Ok)$.
            \end{theorem} 
    The generator matrix of $\Lambda = \sigma(\Ok)$ is defined by:
    
    \begin{equation}
      \label{def:gen-matrix-alg-lattices}
      \begin{pmatrix}
        \sigma_1(\omega_1) & $\dots$ &  \sigma_{r+2s}(\omega_1) \\
        & \vdots & \\
        \sigma_1(\omega_n) & $\dots$ & \sigma_{r+2s}(\omega_n) \\
      \end{pmatrix}  
    \end{equation}
    
            \begin{remark}\label{rem:lat-int-correspondence}
              An embedding creates the correspondence between a point $\lambda \in \Lambda \subset \R^n$ of an algebraic lattice (Theo.
              \ref{theo:algebraic-lattice}) and an integer in $\Ok$:

              Let $\lambda$ be a point of a lattice $\Lambda$:

            \begin{align*} 
                 \lambda &= (\lambda_1,\dots,\lambda_{r+2s}) \in \Lambda \\
                   &= \left( \sum_{i=1}^n{z_i\sigma_1(\omega_i)} , \dots , \sum_{i=1}^n{z_i\sigma_{r+2s}(\omega_i)} \right) \\
                   &= \left( \sigma_1\left(   \sum_{i=1}^n{z_i\omega_i} \right) , \dots , \sigma_{r+2s} \left( \sum_{i=1}^n{z_i\omega_i}  \right) \right) 
            \end{align*}
              where $z_i \in \Z$. Since any element $x \in \Ok$ has the form $x =
              \sum_{i=1}^n{\lambda_i\omega_i}$, we can conclude that:

              \begin{equation*}
                \lambda = \left( \sigma_1(x), \dots, \sigma_{r+2s}(x) \right) = \sigma(x)
              \end{equation*}

            \end{remark}

*** Twisted Embeddings
    
    \begin{definition}
    Let $K$ be a number field with degree $n$ and $\sigma$ an embedding. We say that a number $\tau \in K$ is
    \textbf{totally  positive} if $\forall i \in {1, \dots , n}, \; \sigma_i(\tau) \in \R^*_+$ 
    \end{definition}
    

    \begin{definition}[Twisted Embedding]
      \label{def:twisted-emb}
      Given $\tau$ a totally positive number, the \textbf{$\tau$-twisted embedding}, or
      simply twisted embedding, is the monomorphism defined as:
      \begin{equation*}
        \sigma_\tau(x) = \left( \sqrt{\tau_1}\sigma_1(x), \dots, \sqrt{\tau_{r+2s}}\sigma_{r+2s}(x) \right)
      \end{equation*}

      where $\tau_i = \sigma_i(\tau)$.
    \end{definition}
    
* Objectives 

* Methodology

  \bibliographystyle{plain}
  \bibliography{ic-tese-v3}


 
