#+title: A study of some practical impacts of twisted embeddings in lattice-based cryptography
#+date: March 12, 2021
#+author: Candidate: Laura Viglioni @@latex:\\@@ Supervisor: Prof. Dr. Ricardo Dahab
#+email: l106665@dac.unicamp.br
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [notheorems, bigger]
#+beamer_theme: metropolis
#+options: tex:t toc:nil H:2
#+LATEX_HEADER: \input{./config/math-config}


\begin{frame}{Agenda for this presentation}
\tableofcontents
\end{frame}

* Basic definitions
** Lattices
   A \textbf{lattice} $\Lambda \subset \R^n$ is a subgroup of the additive group $\R^n$.
** Lattices
\begin{text}
  In other words, given $m$ linear independent vectors in $\R^n$, the set
  $\{v_1, v_2, ..., v_m\}$ is called a \textbf{basis} for $\Lambda$ and the lattice may be defined
  by:

  \begin{equation*}
    \Lambda := \left\{x = \sum_{i=1}^m{\lambda_iv_i} \in \R^n \; | \; \lambda_i \in \Z\right\}.
  \end{equation*}

  That is, any $\lambda \in \Lambda$ can be written as $\lambda = Mv$, where $M$ is the
  \textbf{generator matrix} of $\Lambda$ where each row is a vector from the basis and
  $v \in \Z^n$.
\end{text}
** Lattices and cryptography
   In the last two decades, lattice-based cryptosystems have become an important field in the cryptography community, since these cryptosystems rely on mathematical problems we believe are hard and quantum-resistant, such as the Shortest Vector Problem and the Shortest Independent Vectors Problem.
** Lattices problems
*** Gap Shortest Vector Problem
    \begin{text}
      For an approximation factor $\gamma  = \gamma(n) \geq 1$, the $GapSVP_\gamma $ is: given a lattice
      $\Lambda$ and length $d > 0$, output \textbf{YES} if $\lambda_1(\Lambda) \leq d$ and \textbf{NO} if
      $\lambda_1(L) > \gamma d$. 
    \end{text}
*** Shortest Independent Vectors Problem
    \begin{text}
      For an approximation factor $\gamma = \gamma(n) \geq 1$, the $SIVP_\gamma$ is: given a lattice $\Lambda$, output $n$ linearly independent lattice vectors of length at most $\gamma(n) \cdot \lambda_n(\Lambda)$.
    \end{text}
** The /H/ space
   \begin{text}
     Let $r,s,n \in \Z_+$ such that $n = r + 2s > 0$. The space $H \subset \C^n$ is defined
     as:
     \begin{equation*}
       H = \{(a_1,\dots, a_r, b_1,\dots, b_s, \overline{b_1}, \dots, \overline{b_s}) \in \C^n\},
     \end{equation*}

     where $a_i \in \R, \; \forall i \in \{1,\dots,r\}$ and $b_j \in \C, \; \forall \; j \in \{1,\dots,
     s\}$.
   \end{text}
** The /H/ space
   \begin{text}
     For all $x = \left(x_1, \dots, x_n\right), y = \left(y_1, \dots, y_n\right) \in H$ the space
     $H$ is endowed with inner product $\langle {x,y} \rangle_H$ defined as:
     \begin{equation*}
       \langle {x,y} \rangle_H = \sum_{i=1}^n{x_i \overline{y_i}} = \sum_{i=1}^r{x_i y_i} + \sum_{i=1}^s{x_{i+r} \overline{y_{i+r}}} + \sum_{i=1}^s{\overline{x_{i+r}} y_{i+r}}.
     \end{equation*}

     The $\ell_2$-norm and infinity norm of any $x \in H$ are defined as $\|x\| =
     \sqrt{\langle{x,x}\rangle_H}$ and $\|x\|_\infty = \max{\{ |x_i| \}}_{i=1}^n $.
   \end{text}
** Number Fields
   \begin{text}
     For $K, L$ two fields, we denote by $L/K$ a \textbf{field extension} if  $K \subseteq
     L$. Then $L$ is said to be an \textbf{ extension field} over $K$, or just an
     \textbf{extension} over $K$. In a field extension $L/K$, $L$ has the structure of a vector space over $K$.


     A field extension is called a  \textbf{number field} when it is over the rational field $\Q$. 
   \end{text}
** Twisted embeddings
   \begin{text}
     Let $K$ and $L$ be two field extensions and a homomorphism $\phi: K \rightarrow L$. $\phi$ is
     said to be a \textbf{$\Q$-homomorphism} if $\phi(a) = a, ; \forall a \in \Q$.
     \\


     A $\Q$-homomorphism $\phi: K \rightarrow \C$ is called an \textbf{embedding}.
   \end{text}
** Twisted embeddings

   \begin{text}
  
     \begin{theorem}
       If $K$ is a number field with degree $n$ then there are
       exactly $n$ embeddings $\sigma_i : K \rightarrow \C$ where by $\sigma_i(\theta) =
       \theta_i$ where $\theta_i \in \C$ is a distinct zero of $K$'s
       minimum polynomial.
     \end{theorem}

     \tiny Ian Stewart and David Tall.Algebraic number theory. A K Peters, 2002.
   \end{text}
   
** Twisted embeddings
   \begin{text}
     The homomorphism $\sigma: K \rightarrow \R^r \times \C^s$, where $(r,s)$ is the signature of $K$, is the \textbf{canonical embedding} and is defined by:
     \[
     \sigma(x) = \left(\sigma_1(x), \ldots , \sigma_r(x), \sigma_{r+1}(x), \ldots, \sigma_{r+s}(x) \right).
   \]

     Note that we could rewrite the canonical embedding as $\sigma : K \rightarrow \R^n,$

     \begin{align*}
       \sigma(x) = (& \sigma_1(x), \ldots , \sigma_r(x), \\
               & \Re(\sigma_{r+1}(x)), \Im(\sigma_{r+1}(x)), \ldots, \Re(\sigma_{r+s}(x)), \Im(\sigma_{r+s}(x)) ).
     \end{align*}

   \end{text}
** Algebraic lattices
     Let $\{\omega_1,...,\omega_n\}$ be an integral basis of $K$. The $n$ vectors $v_i = \sigma(\omega_i)
\in \R^n$ are linearly independent, so they define a full rank algebraic lattice
$\Lambda = \Lambda(\Ok) = \sigma(\Ok)$.

The generator matrix of \(\Lambda = \sigma(\Ok)\) is defined by

\begin{equation*}
  \label{definition:gen-matrix-alg-lattices}
  \begin{pmatrix}
    \sigma_1(\omega_1) & $\dots$ &  \sigma_{r+2s}(\omega_1) \\
    & \vdots & \\
    \sigma_1(\omega_n) & $\dots$ & \sigma_{r+2s}(\omega_n) \\
  \end{pmatrix}.  
\end{equation*}
** Twisted embeddings and number fields
     
 \begin{text}
   An embedding creates the correspondence between a point $\lambda \in \Lambda \subset \R^n$ of an algebraic lattice.
   \begin{align*} 
     \lambda &= (\lambda_1,\dots,\lambda_{r+2s}) \in \Lambda \\
             &= \left( \sum_{i=1}^n{z_i\sigma_1(\omega_i)} , \dots , \sum_{i=1}^n{z_i\sigma_{r+2s}(\omega_i)} \right) \\
             &= \left( \sigma_1\left(   \sum_{i=1}^n{z_i\omega_i} \right) , \dots , \sigma_{r+2s} \left( \sum_{i=1}^n{z_i\omega_i}  \right) \right), 
   \end{align*}

   where $z_i \in \Z$. Since any element $x \in \Ok$ has the form $x =
   \sum_{i=1}^n{\lambda_i\omega_i}$, we can conclude that

   \begin{equation*}
     \lambda = \left( \sigma_1(x), \dots, \sigma_{r+2s}(x) \right) = \sigma(x).
   \end{equation*}
 \end{text}

* Learning problems
** Learning from Parity
   \begin{text}
     Given $m$ vectors uniformly chosen  $a_i \gets \Z^n_2$ and some $\epsilon \in [0,1]$, we
     define the problem \textbf{Learning from Parity (LFP)} as:

     Find $s \in \Z^n_2$ such that, for $i \in \{1,\dots,m\}$
     $$ \langle{s, a_i}\rangle \; \approx_\epsilon \; b_i \;\; (mod\; 2). $$

     In other words, the equality holds with probability $1 - \epsilon$.
   \end{text}
** Learning with Errors
   \begin{text}
   Learning with Errors (LWE) is a generalization of LFP  with two new parameters
   $p \in \P$ and $\chi$ a probability distribution on $\Z_p$ so that we have:
   \[
     <s, a_i> \; \approx_\chi \; b_i \pmod p \;\;\; \text{or} \;\;\; <s, a_i> + \; e_i =  b_i \pmod p ,
   \]
   where $a_i \gets \Z^n_p$ uniformly and $e_i \gets \Z$ according to $\chi$.
   \end{text}
** Ring-LWE search
   \begin{text}
     Let $K$ be a number field, $R = \Ok$ its ring of integers and $R^\vee$ the
     codifferent ideal of $K$. Also let $K_\R$ be the tensor product $K \otimes_\Q \R$.
  

     Let $\Psi$ be a family of distributions over $K_\R$. The \textbf{search version of the $ring-LWE$ problem}, denoted $R-LWE_{q,\Psi}$, is defined as follows: given access to arbitrarily many independent samples from $A_{s,\psi}$ for some arbitrary $s \in R_q^\vee$ and $\psi \in \Psi$, find $s$.
   \end{text}
** Ring-LWE hardness
   \begin{text}

     \begin{theorem}
       Let K be the $m^{th}$ cyclotomic number field having dimension $n = \phi(m)$ and $R =
       \Ok$ be its ring of integers. Let $\alpha < \sqrt{(\log{n})/n}$, and let $q = q(n)
       \geq 2, \; q = 1 \; (mod \; m)$ be a $poly(n)$-bounded prime such that $\alpha q \geq
       \omega(\sqrt{\log{n}})$. Then there is a polynomial-time quantum reduction from
       $\tilde{O}(n/\alpha)$-approximate $SIVP$ (or $SVP$) on ideal lattices in $K$ to
       $R-DLWE_{q,\Upsilon_\alpha}$.
     \end{theorem}


     \tiny Lyubashevsky, Peikert, and Regev. On ideal lattices and learning with errors over rings.
   \end{text}
   
** Twisted Ring-LWE
   \begin{text}
     For a totally positive element $\tau \in F$, let $\psi_\tau$ denote an error distribution
     over the inner product $\langle{\cdot,\cdot}\rangle_\tau$ and $s \in R^\vee_q$ (the “secret”) be an
     uniformly randomized element. The \emph{Twisted Ring-LWE distribution}
     $\mathcal{A}_{s,\psi_\tau}$ produces samples of the form
     \[
       a, b = a \cdot s + e \pmod{qR^\vee} \in R_q \times K_\R/qR^\vee.
   \]
   \end{text}
** Twisted Ring-LWE hardness
   Solving the Twisted Ring-LWE is as hard as solving the usual Ring-LWE.
   \begin{text}

     \begin{theorem}
       Let $K$ be an arbitrary number field, and let $\tau \in F$ be totally positive.
       Also, let $(s,\psi)$ be randomly chosen from $(U(R_q^\vee)\times \Psi)$ in $(K_\R,\langle{\cdot,\cdot}\rangle_{\tau=1})$.
       Then there is a polynomial-time reduction from $\mbox{Ring-LWE}_{q,\psi}$ to $\mbox{Ring-LWE}^\tau_{q,\psi_\tau}$.
     \end{theorem}

     \tiny Ortiz, Araujo, Aranha, Costa, and Dahab. The Ring-LWE problem in lattice-based cryptography: in praise ofthe twisted embeddings.
   \end{text}
* Twisted Ring-LWE cryptosystem
** Cryptosystem presented by Ortiz et al.
   - Let $R$ be an /m/-th cyclotomic ring and $p, q \in \Z$ coprime numbers.
   - The message space is defined as $R_p$.
   - Consider that $\phi_\tau$ is an error distribution over $\krspace$ and $\lfloor{\cdot}\rceil$ denotes a valid discretization to (cosets) of $R^\vee$ or $pR^\vee$.
   - $\hat{m} = m/2$ if $m$ is even, otherwise $\hat{m} = m$.
   - For any $\overline{a} \in \Z_q$, let $[[\overline{a}]]$ denote the unique representative $a \in (\overline{a} + q\Z) \cap [-q/2, q/2)$, which is entry-wise extended to polynomials.
** Cryptosystem presented by Ortiz et al.
   \begin{itemize}
  \item \textbf{Key generation}: choose a uniformly random $a \in R_q$. Choose $x
    \longleftarrow \lfloor{\phi_\tau}\rceil$ and $e \longleftarrow \lfloor{p \cdot \phi_\tau}\rceil_{pR^\vee}$. Output $(a,b = \hat{m}\cdot(a \cdot x + e)
    \mod{qR} ) \in R_q \times R_q$ as the public key and $x$ as the secret key.
  \item \textbf{Encryption}: choose $z \longleftarrow  \lfloor{\phi_\tau}\rceil_R^\vee$, $e' \longleftarrow \lfloor{p \cdot
      \phi_\tau}\rceil_{pR^\vee}$ and  $e'' \longleftarrow \lfloor{p \cdot \phi_\tau}\rceil_{t^{-1}\mu +pR^\vee}$, where $\mu \in R_p$ is
    the word to be encrypted. Let $u = \hat{m} \cdot (a \cdot z + e') \mod{qR}$ and $v =
    z \cdot b + e'' \in R_q^\vee$. Output $(u,v) \in R_q \times R^\vee_q$.
  \item \textbf{Decryption}: Given the encrypted message $(u,v)$, compute $v - u
    \cdot x \mod{qR^\vee}$, and decode it to $d = [[v - u \cdot x]] \in R^\vee$. Output $\mu = t \cdot
    d \bmod{pR}$. 
  \end{itemize}
* Objectives
** Main goal
   - Validate the idea of using twisted embeddings in cryptography
   - Explore the theoretical and the practical aspects of this proposal
** Practical aspects
   - Compare implementations and instances of the Twisted Ring-LWE and Ring-LWE
   - Maximum real subfield versus the cyclotomic power-of-two
   - Search for proper sizes of keys and messages
** Theoretical aspects
   - Study the polynomial arithmetic of the maximal real subfield
   - Study the relation between the orthonormal basis and the efficient conversion between lattice points and elements of number field
   - Examine if it is possible to achieve a satisfactory efficiency with non-orthonormal basis
* Methodology and timeline
** Methodology
   \begin{itemize}
   \item \textbf{Literature Review:} review proposals of new cryptosystems, such as \emph{NTTRU}.
   \item \textbf{Theoretical experiments:} perform experiments using algebra
     libraries to discover twist factors and to discover orthonormal bases.
   \item \textbf{Experimental outcome:} to calculate the expansion factor of the polynomial \(f(x)\) that defines the ring \(\Z[x]/f(x)\). Adapt or develop algorithms for polynomial multiplication.
   \item \textbf{Implementation:} implement a Twisted Ring-LWE based cryptosystem.
   \item \textbf{Practical experiments:} to estimate the cost in terms of clock cycles, also key and message sizes.
   \end{itemize}
** Timeline
   - First and second semesters of 2021
     - Study the Twisted Ring LWE problem and implementation.
     - Perform theoretical experiments with number fields, twist factors and lattices.
     - Calculate the expansion factor and adapt/develop algorithms for polynomial multiplication.
   - First and second semesters of 2022
     - Implement a Twisted Ring-LWE based cryptosystem.
     - Compare instances of Ring LWE and Twisted Ring LWE, \ie, analyze the cryptosystem in both terms of clock cycles and key sizes.
     - Defense of dissertation.
* Thank you!
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  

  
